### ISSUE TITLE
JS error when you have no images

### ISSUE THREAD

**Issue by devinholloway** [Bastorx/reactjs-coverflow#12]
This is a very minor thing, but I thought I would mention it anyway. If you load up the coverflow component with no images, it produces a js error in the console (it's trying to operate on elements that don't exist).

This would occur in situations such as when the web page first loads up, and you have to make some service calls to get the initial data to populate the coverflow with. So, the component initially loads with no data.

This doesn't really break anything, for once you get the data back and put it in the component, it still works fine. And, you wouldn't even be aware of the error unless you were looking at the console. So, definitely a low priority thing.

**Comment by Bastorx** [comment]
I will produce a patch soon.

For the moment, I invite you to upgrade to 1.0.0 version :)

**Comment by Bastorx** [comment]
Patched 1.0.4
