### ISSUE TITLE
reactjs-coverflow_Mainundefined

### ISSUE THREAD

**Issue by devinholloway** [Bastorx/reactjs-coverflow#14]
Really liking the 1.0 update!

My styles for the "reactjs-coverflow_Main" class stopped working. On further investigation, that class name became "reactjs-coverflow_Mainundefined"

I've temporary worked around it by setting a blank className on the Coverflow:

`<Coverflow ref="coverflow" className="" .../>`

That gets it back to rendering with the "reactjs-coverflow_Main" class name.

**Comment by Bastorx** [comment]
Patched
