### ISSUE TITLE
problems with scrolling

### ISSUE THREAD

**Issue by devinholloway** [Bastorx/reactjs-coverflow#15]
This is a bit of an odd one. The best way to explain it is to show you. Go to:
http://www.westridgephotography.com/new/

The first gallery that loads (Seniors 2015-16) has exactly 66 images. If you then click into the next gallery (Seniors 14), and try to scroll all the way to the end (clicking on the photos is faster than clicking 'next'), it will completely stop scrolling after the 66th image.  Same with any of the other galleries that have more than 66 images... they'll stop scrolling once the 66th image is reached.

In this particular case, when clicking a different gallery, I'm not loading up a new instance of the coverflow component, rather, I'm just loading in a different set of images into the component. So, it appears that, whatever number of images you load into the component originally, you can't scroll past that number even when replacing it with another set of photos.

And by the way... I'm really loving this component so far!

**Comment by Bastorx** [comment]
Ok I see, I didn't see your code but I think that you don't unmount the component.

You dynamically load new image in your component, no ?

I can fix that inside componentWillReceiveProps proprety (I must see newProps.children).

For the moment, try to unmount and remount the component.

I will produce a patch for this situation.

**Comment by devinholloway** [comment]
Right, I just render the component once, and switch out the set of photos on the existing component instance. That also makes sense as to why I have to wait and render the component only after the first service call responds with the default set of photos.

Thanks again for your time and effort writing and updating this component!

**Comment by Bastorx** [comment]
Patched in 1.0.5, you can dynamically load new image (or div) inside the component
